### ISSUE TITLE
Upgrade to RSpec 3

### ISSUE THREAD

**Issue by tioteath** [maxlinc/puppet-decrypt#10]
Trying to perform spec execution:

```
bundle exec rspec
/tmp/src/puppet-crypt/vendor/bundle/ruby/2.1.0/gems/rspec-mocks-3.0.3/lib/rspec/mocks.rb:38:in `setup': wrong number of arguments (1 for 0) (ArgumentError)
    from /tmp/src/puppet-crypt/spec/spec_helper.rb:15:in `<top (required)>'
```

This is probably because of some incompatibility between latest stable `rspec` and `rspec` the specs was developed with.

Could you please specify exact versions for development dependencies in `gemspec`  to eliminate  this issue?

**Comment by maxlinc** [comment]
I was able to upgrade (via transpec) and run rspec without any problems. However, I see several issues open for rspec-puppet saying it has issues with rspec 3. So I'll leave it tied to rspec 2 for now.

Once rspec-puppet is stable on rspec 3, an upgrade should be possible.
